name: Fork repo
on:
  pull_request:
    types: [opened]

jobs:
  comment_on_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Hey There! :wave: Thank you for you contribution! We will get back to review the PR ASAP. Hit on the :star: button for support if you find the repository helpful.
          reactions: star, rocket
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
