name: Fork repo
on:
  watch:
    types: [started]

jobs:
  watch_repo:
    runs-on: ubuntu-latest
    steps: 
      - name: run GitHub cli
        run: |
          gh api \
            --method PUT \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /user/starred/starkblaze01/Algorithms-Cheatsheet-Resources
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
